# Generated by Django 4.1.4 on 2022-12-25 12:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('reserve', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Schedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='予約日')),
                ('seat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reserve.seat', verbose_name='席')),
            ],
        ),
    ]
