# Generated by Django 4.1.4 on 2023-01-02 12:50

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('reserve', '0002_schedule'),
    ]

    operations = [
        migrations.AddField(
            model_name='schedule',
            name='created_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
